before_script:
  - printenv

stages:
  - test

test:
  stage: test
  tags:
    - nas
    - shell
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  before_script:
    - export PATH=$PATH:/home/gitlab-runner/.local/bin
    - pipenv install --dev
  script:
    - pipenv run python3.10 -m coverage run --source='flask_backend,database' -m unittest discover tests
    - pipenv run python3.10 -m coverage report -m --precision=1
  coverage: '/TOTAL.*\s+(\d+\.\d+\%)$/'
