before_script:
  - docker info
  - printenv

stages:
  - test

test:
  stage: test
  image: python:3.10-bullseye
  tags:
    - nas
    - docker
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  before_script:
    - pip3 install pipenv
    - pipenv install --dev
  script:
    - pipenv run coverage run --source='flask_backend,database' -m unittest discover tests
    - pipenv run coverage report -m --precision=1
  coverage: '/TOTAL.*\s+(\d+\.\d+\%)$/'
