before_script:
  - printenv

stages:
  - test

test:
  stage: test
  tags:
    - nas
    - shell
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  before_script:
    - export PATH=$PATH:/home/gitlab-runner/.local/bin
    - pipenv install --dev
  script:
    - pipenv run coverage run -m unittest discover tests
    - pipenv run coverage report
  coverage: '/TOTAL.*\s+(\d+\.\d+\%)$/'
