before_script:
  - docker info
  - printenv

stages:
  - test

test:
  stage: test
  tags:
    - arm64
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  script:
    - pip3 install pipenv
    - export PATH=$PATH:/home/gitlab-runner/.local/bin
    - pipenv install
    - pipenv run python3.10 -m coverage run --source='flask_backend,database' -m unittest discover tests
    - pipenv run python3.10 -m coverage report -m --precision=1
  coverage: '/TOTAL.*\s+(\d+\.\d+\%)$/'
