before_script:
  - printenv

stages:
  - test

test:
  stage: test
  tags:
    - nas
    - shell
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  before_script:
    - python3 -m venv .venv
    - source .venv/bin/activate
    - python3 -m pip install pipenv
    - pipenv install --dev
  script:
    - pipenv run coverage run --source='flask_backend,database' -m unittest discover tests
    - pipenv run coverage report -m --precision=1
  coverage: '/TOTAL.*\s+(\d+\.\d+\%)$/'
